repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: flake8
      name: flake8
      entry: flake8 /home/alex/WIS/Eshop/src
      args: [--config=.flake8]
