version: "3.7"

services:
  web:
    build: ./src
    command: gunicorn Eshop.wsgi:application --bind 0.0.0.0:5000 --reload
    volumes:
      - ./src/:/usr/src/
      - static_data:/usr/src/staticfiles/
      - media_volume:/usr/src/media/
    ports:
      - 5000:5000
    env_file:
      - ./dockers/.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dockers/.env.dev.db

  celery:
    build: ./src
    command: celery -A Eshop worker -l info --logfile=logs/celery.log
    volumes:
      - ./src/:/usr/src/
    env_file:
      - ./dockers/.env.dev
    depends_on:
      - db
      - web
      - redis

  redis:
    image: redis:5-alpine

volumes:
  postgres_data:
  media_volume:
  static_data:
    driver_opts:
      type: none
      o: bind
      device: $PWD
