# Generated by Django 3.1.4 on 2020-12-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='value_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
