# Generated by Django 3.1.4 on 2020-12-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201219_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value_char',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
