# Generated by Django 3.1.4 on 2020-12-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201219_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'permissions': [], 'verbose_name': 'Promo code', 'verbose_name_plural': 'Promo cods'},
        ),
    ]
