# Generated by Django 3.1.4 on 2020-12-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201221_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='attribute',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='value', to='shop.attribute'),
        ),
    ]
