# Generated by Django 3.1.4 on 2020-12-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201222_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='attribute',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='value_model', to='shop.attribute'),
        ),
        migrations.AlterField(
            model_name='value',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='value_model', to='shop.product'),
        ),
    ]
