# Generated by Django 3.1.4 on 2020-12-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201223_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitems',
            name='product',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='shop.product'),
        ),
    ]
