# Generated by Django 3.1.4 on 2020-12-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20201223_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desiredproducts',
            name='items',
        ),
        migrations.AddField(
            model_name='desiredproducts',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='desired_products', to='shop.product'),
        ),
    ]
