# Generated by Django 3.1.4 on 2020-12-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20201223_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredproducts',
            name='product',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='desired_products', to='shop.product'),
        ),
    ]
