# Generated by Django 3.1.4 on 2020-12-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer'),
        ('shop', '0023_auto_20201223_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredproducts',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_products', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='desiredproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_products', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='positionproduct',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_product', to='shop.basket'),
        ),
        migrations.AlterField(
            model_name='positionproduct',
            name='product_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_product', to='shop.productitems'),
        ),
        migrations.AlterField(
            model_name='productscompare',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_compare', to='users.customer'),
        ),
    ]
