# Generated by Django 3.1.4 on 2020-12-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20201224_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age min'),
        ),
        migrations.AddField(
            model_name='product',
            name='age_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age max'),
        ),
    ]
