# Generated by Django 3.1.4 on 2020-12-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20201225_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_character_product', to='shop.attribute'),
        ),
    ]
