# Generated by Django 3.1.4 on 2020-12-27 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20201227_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionproduct',
            name='product_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_product', to='shop.productitems'),
        ),
    ]
