# Generated by Django 3.1.4 on 2020-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20201227_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='positionproduct',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='productitems',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='productscompare',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
