# Generated by Django 3.1.4 on 2020-12-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20201228_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='created', max_length=9),
        ),
    ]
