# Generated by Django 3.1.4 on 2020-12-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20201231_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_character',
            new_name='main_characteristic',
        ),
    ]
