# Generated by Django 3.1.4 on 2020-12-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20201231_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductItems',
            new_name='ProductQuantity',
        ),
    ]
