# Generated by Django 3.1.4 on 2021-01-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20210111_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productquantity',
            options={'permissions': [], 'verbose_name': 'Quantity of a product', 'verbose_name_plural': 'Quantity of products'},
        ),
    ]
